services:
  financas-app:
    image: "marcelobruckner/financas-api:3.2"
    hostname: financas-app
    environment:
      - SERVER_PORT=8080
      - DATABASE_URL=jdbc:mysql://db-mysql:3306/financas
      - DATABASE_USERNAME=root
      - DATABASE_PASSWORD=admin
    depends_on:
      db-mysql:
        condition: service_healthy
    restart: on-failure
    ports:
      - "8080:8080"
    networks:
      - financas-ntw

  db-mysql:
    image: "docker.io/mysql:9"
    hostname: db-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_PASSWORD=admin
      - MYSQL_DATABASE=financas
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    ports:
      - "3306:3306"
    networks:
      - financas-ntw    
networks:
  financas-ntw:    
