services:
  mysql-db:
    container_name: mysql-compose
    image: "docker.io/marcelobruckner/mysql-personal-image:1.0"
    ports:
      - "3306:3306"
  
  financas-app:
    container_name: financas-api-compose
    image: "marcelobruckner/financas-api:3.3"
    environment:
      #- DATABASE_URL=jdbc:mysql://mysql-db:3306/financas
      - DATABASE_URL=jdbc:mysql://mysql-compose:3306/financas
      - DATABASE_USER=app-financas-user
      - DATABASE_PASSWORD=app-financas-pass
    depends_on:
      - mysql-db
    restart: always
    ports:
      - "8080:8080"