apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: build-and-push-pipeline
spec:
  params:
    - name: repo-url
      type: string
    - name: image-url
      type: string
  workspaces:
    - name: shared-data
  tasks:
    - name: clone-repo
      taskRef:
        name: git-clone-personalizado
      params:
        - name: repo-url
          value: "$(params.repo-url)"
      workspaces:
        - name: output
          workspace: shared-data

    #    - name: debug-clone
    #      taskRef:
    #        name: debug-clone
    #      workspaces:
    #        - name: source
    #          workspace: shared-data
    #      runAfter:
    #        - clone-repo

    - name: build-and-push
      taskRef:
        name: build-push
      runAfter:
        - clone-repo
      params:
        - name: image-url
          value: "$(params.image-url)"
      workspaces:
        - name: source
          workspace: shared-data
