apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: git-clone-personalizado
spec:
  params:
    - name: repo-url
      type: string
    - name: revision
      type: string
      default: "main"
  workspaces:
    - name: output
  steps:
    - name: clone
      image: alpine/git
      script: |
        #!/bin/sh
        set -e
        echo "Clonando repositório $(params.repo-url)..."
        git clone -b $(params.revision) $(params.repo-url) $(workspaces.output.path)/repo
        echo "Arquivos clonados:"
        ls -lah $(workspaces.output.path)/repo
