apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: toolkit
  namespace: tekton-builds
spec:
  params:
    - name: project
      default: financas
    - name: release
      default: "1.0.1"
  workspaces:
    - name: pipeline-ws
  tasks:
    - name: task-echo
      taskRef:
        name: task-echo
      workspaces:
        - name: source
          workspace: pipeline-ws
      params:
        - name: message
          value: IAE VAGABOND!
