apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: financas-deployment
  name: financas
spec:
  replicas: 1
  selector:
    matchLabels:
      app: financas-deployment
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: financas-deployment
    spec:
      containers:
        - image: default-route-openshift-image-registry.apps-crc.testing/financas/financas-api:latest
          name: financas-api
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: "0.75"
              memory: 512Mi
            requests:
              cpu: "0.50"
              memory: 256Mi
