apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: financas-deployment
  labels:
    app: financas-deployment
spec:
  to:
    kind: Service
    name: financas-deployment
  port:
    targetPort: 8080
  tls:
    termination: edge
  wildcardPolicy: None
