apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: financas-deployment
  name: financas-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: financas-deployment
  strategy: {}
  template:
    metadata:
      labels:
        app: financas-deployment
    spec:
      containers:
      - image: marcelobruckner/financas-api:3.3
        name: financas-api
        ports:
        - containerPort: 8080
        env:
        - name: DATABASE_URL
          value: "jdbc:mysql://mysql-service:3306/financas"
        - name: DATABASE_USER
          value: "app-financas-user"
        - name: DATABASE_PASSWORD
          value: "app-financas-pass"