apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  database-url: amRiYzpteXNxbDovL215c3FsLXNlcnZpY2U6MzMwNi9maW5hbmNhcw== #jdbc:mysql://mysql-service:3306/financas
  database-user: YXBwLWZpbmFuY2FzLXVzZXI= #app-financas-user
  database-password: YXBwLWZpbmFuY2FzLXBhc3M= #app-financas-pass
